### ISSUE TITLE
Make more suitable for npm publishing

### ISSUE THREAD

**Issue by uosl** [intermine/generator-bluegenes-tool#14]
Suggestions for improvements:
- Add `.npmignore` file that excludes the *src* directory (I think only *dist* is required when using a tool as an npm package)
- Add `prepack` script to `package.json` so we don't manually have to build on every `npm publish` (`prepack` seems to be the most suitable script to use, according to https://docs.npmjs.com/misc/scripts)

**Comment by akshatbhargava123** [comment]
Do we need to build the `dist` folder in `prepack`?

**Comment by uosl** [comment]
1. Yes, we need `dist` to be included in our npm package.
2. I think `package.json` and `config.json` needs to be available as well (@yochannah can confirm).

**Comment by yochannah** [comment]
Correct on both counts! Also, ideally preview.png (but that's not mandatory)

**Comment by pooja2299** [comment]
Hi @yochannah I am an Outreachy aspirant. I have basic knowlegde on html,css and js. Can i give this issue a try? Need ur guidance how to begin with it.

**Comment by yochannah** [comment]
@pooja2299 for **prepack**, we'll to automatically run the same commands as npm build - the idea being that way we can be sure that any build scripts have been run _before_ we publish the package. A tiny bit of info here: https://docs.npmjs.com/misc/scripts - the yarn guide talks about it a little, too: https://yarnpkg.com/advanced/lifecycle-scripts 

for npmignore, we want to exclude files from being published on npm that aren't relevant. See http://npm.github.io/publishing-pkgs-docs/publishing/the-npmignore-file.html - see the discussions above about which files / folders to ignore. You'll need to create the `.npmignore` file yourself in the root of the repo, and check it in on git. DM me on the chat if needed <3
