### ISSUE TITLE
Tool linter / validator?

### ISSUE THREAD

**Issue by yochannah** [intermine/generator-bluegenes-tool#17]
Or even just ESLint in the scaffolder?

**Comment by uosl** [comment]
Closing this as it was added in https://github.com/intermine/generator-bluegenes-tool/pull/7.

**Comment by yochannah** [comment]
@uosl this wasn't what I meant actually 😆 so much as a way of checking that a tool can successfully run in bluegenes - e.g. it takes an id or ids and produces results, provides the correct arguments so bluegenes knows what to do, etc. Sorry - it was clear in my brain but I can see why you would think it was referring to eslint!

**Comment by yochannah** [comment]
wait, this should be a separate issue. Ignore that.
