### ISSUE TITLE
fix failing linting

### ISSUE THREAD

**Issue by yochannah** [intermine/generator-bluegenes-tool#4]
`npm run test` fails with 

```
Invalid name: "@intermine/<%=toolNameNpm%>"
```
We don't appear to pass linting. Let's try to fix this.

**Comment by yochannah** [comment]
Thanks @akshatbhargava123 for noticing this!

**Comment by yochannah** [comment]
Fixed by #3

**Comment by akshatbhargava123** [comment]
Actually, the error shared by you doesn't seem to appear. Expect `dev/serve.js` (for which I've already created a PR), we are also missing to copy `TODO.md`, salute to unit testing.
I just added a line to copy that, and all tests passed.

**Comment by yochannah** [comment]
your original PR did fix my error though! lol

**Comment by akshatbhargava123** [comment]
Haha, alright. Creating another to clear the `test`.

**Comment by akshatbhargava123** [comment]
#5 results in PASSed test.
